# GPHY 491-591: Lab 2 
Written by Cascade Tuholske, Jan. 2024  

### <u> Goals <u>
The goal of this lab is to pratice writing code with numpy, pandas, and matplotlib using a real-world dataset. The dataset was developed to understand the relationship between child undernutrition, measured by [USAID Demographic and Health Surveys](https://www.usaid.gov/global-health/demographic-and-health-surveys-program), and national-level indicators of economic development. Child undernutrition is often broken into two categories: low weight for age (stunting - reflecting chronic food insecurity) and low weight for height (wasting - reflecting acute food insecurity). <br>
    
Orthodox theories of economic development posit that as a country urbanizes, its economy grows and food security improves. Thus, more urbanized countries should be more food secure compared to more rural countries. Further, within a country, urban areas should be more food secure compared to rural areas.<br>
    
We will explore this dataset to understand if economic development and food security are well-correlated, and see what proxy indecators of economic development may also correlate with child food insecurity. <br>
    
### <u> Instruction <u>
1. Please rename your notebook as: `Last_First_Lab1` **NOTE:** Naming convetions matter for files, including notebooks and data. Always be consistant. 
2. Complete lab by writing code or answering questions in the cells as in structed by the comments.
3. Copy your notebook to `/home/YOURNETID/gphy591/submissions/`

# Let's import our packages
![import](assets/import.png)

In [1]:
# Packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os # this package allows us to interface with out opperating system

## Let's load the .csv file with pandas and explore it.

In [3]:
# we write file paths and names as their own variables for easy editing
fn = os.path.join('../../GPHY-491-591/data/DhsPrevalenceWCovar.csv')
type(fn) # see that our fn is a string, but the os.path.join also helps Python know it's a file path

str

In [5]:
# open the data frame and check it
df = pd.read_csv(fn)
df.head(4) # show first four rows

,country,year,countryCode,continent,stunt_rural,stunt_urban,waste_rural,waste_urban,stunt_all,waste_all,...,foodExport,foodImport,gdpPPP,gdpPPPpercap,giniIndex,urbanPop,urbanPopGrowth,clusterPrecipAnom,nationalTempAnom,nationalPrecipAnom
0,Albania,2008,ALB,Europe,0.240576,0.244390,0.092801,0.124743,0.242117,0.105710,...,4.333982,16.432549,2.921436e+10,9912.196804,30.0,49.991,1.435124,86.245678,102.151715,102.020721
1,Albania,2009,ALB,Europe,0.240576,0.244390,0.092801,0.124743,0.242117,0.105710,...,5.669017,17.087390,3.019429e+10,10313.952000,NaN,51.076,1.473288,132.170168,100.470106,134.103392
2,Armenia,2000,ARM,Asia,0.238902,0.178222,0.019989,0.034612,0.207806,0.027483,...,13.493826,24.967986,1.242650e+10,3921.857522,NaN,64.666,-1.610375,NaN,102.973351,74.551193
3,Armenia,2005,ARM,Asia,0.190440,0.214489,0.033354,0.081562,0.204712,0.061964,...,13.361364,17.662960,2.212058e+10,7259.203892,36.0,63.938,-0.761535,NaN,100.503031,114.152255

In [7]:
# write a for loop that prints all the column names sorted by first letter
for column in sorted(df.columns):
    print(column)

agLabor
agLand
clusterPrecipAnom
continent
country
countryCode
electricity
foodExport
foodImport
gdpPPP
gdpPPPpercap
giniIndex
nationalPrecipAnom
nationalTempAnom
stunt_all
stunt_rural
stunt_urban
urbanPop
urbanPopGrowth
waste_all
waste_rural
waste_urban
year

In [ ]:
# What is the shape of the data frame?

In [ ]:
# Print the data type for each column.

In [ ]:
# Which rows are missing data?

Our dataset is organized in survey-year-country rows. This means that each year is a single survey for a single country. All the metrics are national-level, meaning that stunting or wasting are rates (e.g. prevelance).

In [13]:
# Which country-year had the highest stunting prevalence for all households?
df.loc[df['stunt_all'].idxmax()]

country                  Madagascar
year                           1992
countryCode                     MDG
continent                    Africa
stunt_rural                0.661545
stunt_urban                0.540161
waste_rural                0.056063
waste_urban                0.038153
stunt_all                  0.643071
waste_all                  0.053337
electricity                     9.2
agLand                     62.54084
agLabor                    76.52773
foodExport                68.219322
foodImport                13.392456
gdpPPP                20375253257.0
gdpPPPpercap             1614.09342
giniIndex                       NaN
urbanPop                     24.681
urbanPopGrowth              5.34426
clusterPrecipAnom               NaN
nationalTempAnom          98.684006
nationalPrecipAnom        97.005517
Name: 164, dtype: object

In [19]:
# Which country-year had the lowest stunting prevalence for all households?

In [18]:
# How many surveys were conducted in Senegal?
geog = 'Senegal'
df_ = df[df['country'] == geog]
len(df_)

13

In [ ]:
# What years were surveys conducted in Senegal?

In [ ]:
# Using for loops, print the year of the year and prevalence ranked highest to lowest for urban wasting for senegal.

In [21]:
# Another way to do this, is using the built-in methods to a pandas data frame 'sort_values'
df_.sort_values('waste_urban', ascending = True)

,country,year,countryCode,continent,stunt_rural,stunt_urban,waste_rural,waste_urban,stunt_all,waste_all,...,foodExport,foodImport,gdpPPP,gdpPPPpercap,giniIndex,urbanPop,urbanPopGrowth,clusterPrecipAnom,nationalTempAnom,nationalPrecipAnom
254,Senegal,2005,SEN,Africa,0.261728,0.132712,0.093712,0.054209,0.215923,0.079687,...,28.822376,28.139253,3.059048e+10,2787.526892,39.2,41.714,3.524171,125.195587,101.439134,126.935953
259,Senegal,2014,SEN,Africa,0.238132,0.138905,0.078681,0.057028,0.196129,0.069515,...,34.770632,22.781849,4.065763e+10,2910.288864,NaN,45.436,3.641058,80.864364,100.774577,92.088913
252,Senegal,1992,SEN,Africa,0.375175,0.221325,0.107293,0.065428,0.303679,0.087838,...,NaN,NaN,1.935822e+10,2427.510861,NaN,39.180,3.163572,77.040678,98.916989,86.186147
253,Senegal,1993,SEN,Africa,0.375175,0.221325,0.107293,0.065428,0.303679,0.087838,...,NaN,NaN,1.962153e+10,2393.876688,NaN,39.321,3.105499,89.573768,99.348917,91.113471
261,Senegal,2016,SEN,Africa,0.204598,0.117589,0.096573,0.065653,0.172423,0.085139,...,32.219563,23.351211,4.599509e+10,3118.024321,NaN,46.296,3.657310,102.335350,101.327314,107.057383
264,Senegal,2019,SEN,Africa,0.216055,0.118986,0.096465,0.070286,0.180561,0.086893,...,32.918857,19.609161,5.489042e+10,3430.483882,NaN,47.653,3.669750,89.929804,101.443553,80.234835
263,Senegal,2018,SEN,Africa,0.230304,0.126899,0.094745,0.071734,0.191035,0.086006,...,32.292665,21.043717,5.246967e+10,3368.858596,38.3,47.192,3.677055,90.003551,100.221001,99.761651
260,Senegal,2015,SEN,Africa,0.248579,0.149995,0.099807,0.079801,0.212271,0.092439,...,31.359992,21.688935,4.324632e+10,3012.383374,NaN,45.862,3.657857,122.997624,100.606463,103.153827
262,Senegal,2017,SEN,Africa,0.210724,0.107988,0.107297,0.081294,0.172995,0.097748,...,34.231624,23.989994,4.940217e+10,3259.192580,NaN,46.740,3.672445,98.506265,101.286283,105.490621
257,Senegal,2012,SEN,Africa,0.220837,0.167896,0.115063,0.082925,0.204458,0.105121,...,26.848014,24.145794,3.737375e+10,2824.532853,NaN,44.603,3.661748,131.155050,99.905978,120.996972
258,Senegal,2013,SEN,Africa,0.220837,0.167896,0.115063,0.082925,0.204458,0.105121,...,34.031309,24.228372,3.827535e+10,2815.281525,NaN,45.019,3.640180,103.492852,100.715139,110.125771
255,Senegal,2010,SEN,Africa,0.324836,0.274109,0.101248,0.115013,0.306920,0.106110,...,26.756547,22.408693,3.546216e+10,2830.153244,NaN,43.773,3.660986,145.656817,102.095910,133.983894
256,Senegal,2011,SEN,Africa,0.324836,0.274109,0.101248,0.115013,0.306920,0.106110,...,30.540866,22.945852,3.593526e+10,2790.897410,40.3,44.188,3.665644,90.184774,101.440277,94.245435

In [23]:
# You can look at all the available functions using the key word 'dir'
dir(df_)

In [25]:
# You can use 'help' to understand objects, methods, functions, etc.
# Parameters (also called 'arguments') are the objects you pass to a function before you 'call it'
help(df_.sort_values)

Help on method sort_values in module pandas.core.frame:

sort_values(by: 'IndexLabel', *, axis: 'Axis' = 0, ascending: 'bool | list[bool] | tuple[bool, ...]' = True, inplace: 'bool' = False, kind: 'str' = 'quicksort', na_position: 'str' = 'last', ignore_index: 'bool' = False, key: 'ValueKeyFunc' = None) -> 'DataFrame | None' method of pandas.core.frame.DataFrame instance
    Sort by the values along either axis.

    Parameters
    ----------
            by : str or list of str
                Name or list of names to sort by.

                - if `axis` is 0 or `'index'` then `by` may contain index
                  levels and/or column labels.
                - if `axis` is 1 or `'columns'` then `by` may contain column
                  levels and/or index labels.
    axis : {0 or 'index', 1 or 'columns'}, default 0
         Axis to be sorted.
    ascending : bool or list of bool, default True
         Sort ascending vs. descending. Specify list for multiple sort
         orders.  If this is a list of bools, must match the length of
         the by.
    inplace : bool, default False
         If True, perform operation in-place.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, default 'quicksort'
         Choice of sorting algorithm. See also :func:`numpy.sort` for more
         information. `mergesort` and `stable` are the only stable algorithms. For
         DataFrames, this option is only applied when sorting on a single
         column or label.
    na_position : {'first', 'last'}, default 'last'
         Puts NaNs at the beginning if `first`; `last` puts NaNs at the
         end.
    ignore_index : bool, default False
         If True, the resulting axis will be labeled 0, 1, â€¦, n - 1.

         .. versionadded:: 1.0.0

    key : callable, optional
        Apply the key function to the values
        before sorting. This is similar to the `key` argument in the
        builtin :meth:`sorted` function, with the notable difference that
        this `key` function should be *vectorized*. It should expect a
        ``Series`` and return a Series with the same shape as the input.
        It will be applied to each column in `by` independently.

        .. versionadded:: 1.1.0

    Returns
    -------
    DataFrame or None
        DataFrame with sorted values or None if ``inplace=True``.

    See Also
    --------
    DataFrame.sort_index : Sort a DataFrame by the index.
    Series.sort_values : Similar method for a Series.

    Examples
    --------
    >>> df = pd.DataFrame({
    ...     'col1': ['A', 'A', 'B', np.nan, 'D', 'C'],
    ...     'col2': [2, 1, 9, 8, 7, 4],
    ...     'col3': [0, 1, 9, 4, 2, 3],
    ...     'col4': ['a', 'B', 'c', 'D', 'e', 'F']
    ... })
    >>> df
      col1  col2  col3 col4
    0    A     2     0    a
    1    A     1     1    B
    2    B     9     9    c
    3  NaN     8     4    D
    4    D     7     2    e
    5    C     4     3    F

    Sort by col1

    >>> df.sort_values(by=['col1'])
      col1  col2  col3 col4
    0    A     2     0    a
    1    A     1     1    B
    2    B     9     9    c
    5    C     4     3    F
    4    D     7     2    e
    3  NaN     8     4    D

    Sort by multiple columns

    >>> df.sort_values(by=['col1', 'col2'])
      col1  col2  col3 col4
    1    A     1     1    B
    0    A     2     0    a
    2    B     9     9    c
    5    C     4     3    F
    4    D     7     2    e
    3  NaN     8     4    D

    Sort Descending

    >>> df.sort_values(by='col1', ascending=False)
      col1  col2  col3 col4
    4    D     7     2    e
    5    C     4     3    F
    2    B     9     9    c
    0    A     2     0    a
    1    A     1     1    B
    3  NaN     8     4    D

    Putting NAs first

    >>> df.sort_values(by='col1', ascending=False, na_position='first')
      col1  col2  col3 col4
    3  NaN     8     4    D
    4    D     7     2    e
    5    C     4     3    F
    2    B     9     9    c
    0    A     2     0    a
    1    A     1     1    B

    Sorting with a key function

    >>> df.sort_values(by='col4', key=lambda col: col.str.lower())
       col1  col2  col3 col4
    0    A     2     0    a
    1    A     1     1    B
    2    B     9     9    c
    3  NaN     8     4    D
    4    D     7     2    e
    5    C     4     3    F

    Natural sort with the key argument,
    using the `natsort <https://github.com/SethMMorton/natsort>` package.

    >>> df = pd.DataFrame({
    ...    "time": ['0hr', '128hr', '72hr', '48hr', '96hr'],
    ...    "value": [10, 20, 30, 40, 50]
    ... })
    >>> df
        time  value
    0    0hr     10
    1  128hr     20
    2   72hr     30
    3   48hr     40
    4   96hr     50
    >>> from natsort import index_natsorted
    >>> df.sort_values(
    ...    by="time",
    ...    key=lambda x: np.argsort(index_natsorted(df["time"]))
    ... )
        time  value
    0    0hr     10
    3   48hr     40
    2   72hr     30
    4   96hr     50
    1  128hr     20

In [46]:
# You can also summerize each column easily
df_.describe()

,year,stunt_rural,stunt_urban,waste_rural,waste_urban,stunt_all,waste_all,electricity,agLand,agLabor,...,foodImport,gdpPPP,gdpPPPpercap,giniIndex,urbanPop,urbanPopGrowth,clusterPrecipAnom,nationalTempAnom,nationalPrecipAnom,agLabor-to-agLand
count,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,12.000000,13.000000,13.000000,...,11.000000,1.300000e+01,13.000000,3.000000,13.000000,13.000000,13.000000,13.000000,13.000000,11.000000
mean,2010.384615,0.265524,0.170749,0.101115,0.077441,0.228573,0.091966,56.975000,47.231001,35.722666,...,23.121167,3.871370e+10,2920.693161,39.266667,44.382846,3.569021,103.610499,100.732426,103.951913,1.062030
std,8.761074,0.062270,0.058279,0.009774,0.019087,0.054890,0.011462,11.389399,1.235435,9.211719,...,2.182189,1.106010e+10,317.106198,1.001665,2.765506,0.197083,21.152221,0.921880,15.986811,0.271062
min,1992.000000,0.204598,0.107988,0.078681,0.054209,0.172423,0.069515,26.000000,45.582507,22.245040,...,19.609161,1.935822e+10,2393.876688,38.300000,39.180000,3.105499,77.040678,98.916989,80.234835,0.688857
25%,2010.000000,0.220837,0.126899,0.096465,0.065428,0.191035,0.086006,56.500000,46.564172,31.261260,...,22.048814,3.546216e+10,2790.897410,38.750000,43.773000,3.640180,89.929804,100.221001,92.088913,0.884279
50%,2013.000000,0.238132,0.149995,0.101248,0.071734,0.204458,0.087838,58.750000,46.600530,34.864730,...,22.945852,3.827535e+10,2830.153244,39.200000,45.019000,3.657857,98.506265,100.774577,103.153827,1.024490
75%,2016.000000,0.324836,0.221325,0.107293,0.082925,0.303679,0.105121,62.400000,48.423622,38.188450,...,24.067894,4.599509e+10,3118.024321,39.750000,46.296000,3.665644,122.997624,101.439134,110.125771,1.284042
max,2019.000000,0.375175,0.274109,0.115063,0.115013,0.306920,0.106110,70.400000,48.797590,52.201060,...,28.139253,5.489042e+10,3430.483882,40.300000,47.653000,3.677055,145.656817,102.095910,133.983894,1.444910

## New Columns
You can easily make new columns in a Pandas DateFrame using simple math.

In [26]:
# Make a new column that is the ratio of agLabor to agLand
df_['agLabor-to-agLand'] = df_['agLabor'] / df_['agLand']

/var/folders/1q/4fd5w5_d5m3_l087yl0p7kt46wjsmq/T/ipykernel_28245/92771218.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_['agLabor-to-agLand'] = df_['agLabor'] / df_['agLand']

The warning is important. **Always** read about warnings before deciding if you are okay with moving forward. In this case, we are okay to continue.

In [ ]:
# what kind of data is df_['agLabor-to-agLand']?

In [32]:
# Let's round our data two 2 decimals
df_['agLabor-to-agLand'] = df_['agLabor-to-agLand'].round(2)

/var/folders/1q/4fd5w5_d5m3_l087yl0p7kt46wjsmq/T/ipykernel_28245/578438654.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_['agLabor-to-agLand'] = df_['agLabor-to-agLand'].round(2)

In [35]:
# what kind of data is df_['agLabor-to-agLand'] now?
df_['agLabor-to-agLand']

252    1.14
253    1.14
254    0.91
255    0.79
256    0.80
257    0.78
258    0.75
259    0.71
260    0.65
261    0.71
262    0.58
263    0.46
264    0.47
Name: agLabor-to-agLand, dtype: float64

In [36]:
# Let's change it to save memory
df_['agLabor-to-agLand'] = df_['agLabor-to-agLand'].astype('float32')

/var/folders/1q/4fd5w5_d5m3_l087yl0p7kt46wjsmq/T/ipykernel_28245/1295747487.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_['agLabor-to-agLand'] = df_['agLabor-to-agLand'].astype('float32')

### Let's do the same, but for agLabor to foodExport

In [49]:
# Make a new column that is the ratio of agLabor to agLand
df_.loc[:, 'agLabor-to-foodExport'] = df_['agLabor'] / df_['foodExport']

In [ ]:
describe()

Notice `.loc` removes the warning. You are now doing proper indexing under the latest version of Pandas.

## Now explore a bit yourself

Which country and what year did the highest [gdp ppp](https://www.cia.gov/the-world-factbook/field/real-gdp-purchasing-power-parity/country-comparison#:~:text=A%20nation%27s%20GDP%20at%20purchasing,prevailing%20in%20the%20United%20States.) happen?

In [50]:
# Code here. (note: you should us the df object, not df_)

Across all years, what is the correlation between gdp ppp and stunting? <br> Hint - you can try `np.corrcoef(x, y)`

In [50]:
# Code here.

Across all years, what is the correlation between gdp ppp and stunting for surveys conducted after 2000? <br> Hint - you can subset your DataFrame by year with `df[df[year > 2000]`

In [50]:
# Code here.

# Let's do some plots

In [ ]:
# Make a scatter plot of the relationship between GPD PPP and All Stunting

In [ ]:
# Make a scatter plot of the relationship between GPD PPP and Urban Stunting

In [ ]:
# Make a scatter plot of the relationship between GPD PPP and Rural Stunting

In [ ]:
# Make a scatter plot of the relationship between GPD PPP with both Urban and Rural Stunting plotted 
# on the same plot

FYI: UrbanPop is the percentage of the total population classified as 'urban'.

In [ ]:
# Make a three panel figure with panel (A) the relationship between UrbanPop and All wasting 
# panel (B) the relationship between UrbanPop and rural wasting, and panel (C) the relationship 
# between UrbanPop and urban wasting.

### Take some time to read about the package [Seaborn](https://seaborn.pydata.org)

In [ ]:
import seaborn as sns

In [ ]:
# Try making a histogram of GPD PPP using Seaborn

In [ ]:
# Try making a scatter plot of the relationship between GPD PPP and All Stunting 
# with the regression line using seaborn using Seaborn

In [ ]:
# Try making a pairplot of GPD PPP, UrbanPop, AgLabor, All Stunting, Rural Stunting, and Urban Stunting

# Questions

### Question 1: Which variables are most highly correlated: GPD PPP, UrbanPop, AgLabor, All Stunting, Rural Stunting, and Urban Stunting? What about  Provide evidence to support your conclusions.

Answer:

### Question 2: Which variables are most highly correlated: GPD PPP, UrbanPop, AgLabor, All Wasting, Rural Wasting, and Urban Wasting? What about  Provide evidence to support your conclusions.

Answer:

### Question 1: Which variables are most highly correlated: GPD PPP, UrbanPop, AgLabor, All Stunting, Rural Stunting, and Urban Stunting? What about  Provide evidence to support your conclusions.

Answer: